### PR TITLE
Don't broadcast messages if you can't process them

### LINKED ISSUE #288: Stop all runner processing if an instance is stopped
### Description

If an instance is stopped, we should also stop/prevent:
- [ ] broadcasting messages
- [ ] postconsensus processing
- [ ] preconsensus processing

### PR DESCRIPTION
**Pull request by GalRogozinski**
fix #288

### CODE REVIEW

**Comment by GalRogozinski** [comment]
Tests will come at a later PR

**Comment by y0sher** [comment]
> Tests will come at a later PR

IMO if you planning to have tests its better to have them aside the code.

**Review by y0sher — APPROVED** [review]
Approving code but again IMO you should add at least one test.

**Comment by GalRogozinski** [comment]
@y0sher 

When we did #274 we didn't add tests. Now we are closing some holes and another PR will concentrate all tests

**Comment by GalRogozinski** [comment]
This doesn't have to be a part of the spec tat attempts to be minimalistic.
A node can choose to not broadcast a message and it won't be a fork.

**Pull request closed without merging**
