### PR TITLE
Post-consensus test: Duplicate message then quorum test

### PR DESCRIPTION
**Pull request by MatheusFranco99**
- [x] Post-consensus - DuplicateMsg and then quorum. The test asserts that the error doesn't disallow terminating a duty after a quorum is reached.

### CODE REVIEW

**Review by GalRogozinski — APPROVED** [review]
Nice!

**Comment by GalRogozinski** [comment]
refers to #264

**Review by moshe-blox — APPROVED** [review]
LGTM

**Review by y0sher — APPROVED** [review]

**Review by GalRogozinski — CHANGES_REQUESTED** [review]
Hey @MatheusFranco99 

Don't want to do changes in your PR myself (besides merging and resolving conflicts).
Shouldn't the tests here be "Duplicate message with different roots then quorum"...

It is just that we have `duplicate_msg.go` and `duplicate_msg_different_root.go` and this test seems like an extension of the latter...

maybe other good tests will be to create quorum of dup messages and a test with one dup message that has the same root (not for this PR)

**Comment by MatheusFranco99** [comment]
Hey @GalRogozinski 
The test is indeed a duplicate message (from an already received signer) with a different signing root and then the operator receives a quorum successfully.

You mean that a more appropriate test name (and file name) should include something like "msg different root", correct?
I agree. Will wait on your response to change it :)

**Comment by GalRogozinski** [comment]
@MatheusFranco99 yes

**Comment by MatheusFranco99** [comment]
@GalRogozinski done

**Review by GalRogozinski — APPROVED** [review]

**Pull request merged**
